[book]
authors = ["YARlabs"]
language = "en"

src = "src"
title = "NietzscheDBDB Documentation"

[output.html]
mathjax-support = true
default-theme = "navy"
site-url = "/nietzsche-db/"
git-repository-url = "https://github.com/yarlabs/nietzsche-db"
