[package]
name = "nietzsche-query"
version = "0.1.0"
edition = "2021"
description = "NQL - Nietzsche Query Language parser, planner and executor"

[dependencies]
nietzsche-graph = { workspace = true }
hyperspace-core = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
