[package]
name        = "nietzsche-query"
version     = "0.1.0"
edition     = "2021"
description = "NQL â€” Nietzsche Query Language: PEG parser, planner, and executor"

[dependencies]
nietzsche-graph = { workspace = true }
nietzsche-dsi   = { path = "../nietzsche-dsi" }
pest            = { workspace = true }
pest_derive     = { workspace = true }
serde           = { workspace = true }
thiserror       = { workspace = true }
uuid            = { workspace = true }
bincode         = { workspace = true }
serde_json      = "1.0"
rayon           = "1.10"
regex           = "1"

[dev-dependencies]
tempfile = "3"
