[package]
name = "nietzsche-sdk"
version = "0.1.0"
edition = "2021"
description = "Rust async client SDK for NietzscheDB (gRPC)"

[dependencies]
nietzsche-api = { workspace = true }
tonic         = { workspace = true }
prost         = { workspace = true }
serde         = { workspace = true }
serde_json    = "1.0"
tokio         = { workspace = true }
uuid          = { workspace = true }
rand          = { workspace = true }

[[example]]
name = "seed_100"
path = "examples/seed_100.rs"
